### ISSUE TITLE
bug: Failed to fetch dynamically imported module: https://localhost:3000/_nuxt/node_modules/shadcn-docs-nuxt/pages/index.vue

### ISSUE THREAD

**Issue by nikeshparajuli** [ZTL-UwU/shadcn-docs-nuxt#10]
Hi, thank you for your project! I am not able to use it due to some errors. When I install your project using bun, it reports that it's not able to find the component/ui directory and gives me a 500 error when I start the development server. I have attached some screenshots for your reference. Would you mind taking a look?

Things I have tried:
- using npm instead of bun
- manually copy/pasting the components directory and the components.json file (which should be included in the bundle and it does but it's looking for it in my project directory somewhere). Adding those two results in all sorts of errors due to duplicate components being found from node_modules and my project directory.

![CleanShot 2024-06-26 at 23 12 32](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/47485043/8fde2f22-e45c-49eb-b97f-e85680fba0b4)

![CleanShot 2024-06-26 at 23 16 27](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/47485043/46318691-0e55-41b2-908a-0808073dda7f)

![CleanShot 2024-06-26 at 23 18 55](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/47485043/ed78fd87-bf66-410f-acfd-4b52bdd2733d)

**Comment by ZTL-UwU** [comment]
@nikeshparajuli you can try reinstalling like mentioned in #9.

The `components/ui` not found warning is expected. I think this is because the shacn-nuxt module scanning the directory in the base layer as well. But presently I don't know how it can be fixed so just ignore it for now 🙈

**Comment by nikeshparajuli** [comment]
Hi @ZTL-UwU, I tried that and still get the same error.

**Comment by ZTL-UwU** [comment]
@nikeshparajuli I can only reproduce this in cloud dev environments (github codespace & gitpod) but not locally. If you are running the project in a cloud dev environment, you can try setting all the forwarded ports to public. It fixes the problem for me in both gitpod & github codespace.

**Comment by nikeshparajuli** [comment]
Hi @ZTL-UwU, I'm running this locally (M1 Mac) not in cloud.

**Comment by ZTL-UwU** [comment]
![image](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/49156174/be307c27-c820-4a9b-8aaf-56ae887adec3)
![image](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/49156174/dc94a961-5aef-4d38-8282-fb8261fd6c39)
Can you check your browser console to see if there are errors similar to these?

**Comment by nikeshparajuli** [comment]
I don't see those errors. The WS connection is successful on my side.

![CleanShot 2024-06-28 at 12 11 03](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/47485043/c89fdee3-a4e1-40ce-a039-afea6ce144a8)

**Comment by ZTL-UwU** [comment]
I have no idea why this is happening. Maybe disabling hmr is a temporary work around?

**Comment by nikeshparajuli** [comment]
Hi @ZTL-UwU, turns out my ad-blocker (ublock origin) is the culprit. After I disabled it, I can at least get past the 500 error and see the homepage. There are other console warnings and an error but apart from that, it's all good now.
