### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by crearis** [ZTL-UwU/shadcn-docs-nuxt#11]
Hello Tony Zhang,

thanks for your impressing work here!
I am searching for a robust starting-point to make shadcn-vue go the nuxt way - and your project seems very promising.
I understand your motivation as well. The paid nuxt ui pro can be blocking as any commercial licencing ...

As soon as we don't have the thing licensed clearly under an OpenSource-license trouble might arise sooner or later.

My simple question: Do you need to make this argument, that it is 'too much to pay' for nuxt ui pro? To me this sounds somehow aggressive.

I think it is absolutely enough motivation to have a "completely open-sourced fully-fledged docs-template based on shadcn".

It's just an opinion though - keep up the good work!!
Hans

**Comment by crearis** [comment]
As this is just my opinion and not a request to change anything, I'll close this. I hop I'll figure out how I could support your repo anyhow.

**Comment by AsyncFox** [comment]
Hello Hans,

Thanks for your kind words and understanding!

I’m writing as a friend and teammate of Tony Zhang to provide some additional context. As students in China, the cost of Nuxt UI Pro is a significant factor for us. To put it into perspective, the solo plan at 249 dollars translates to roughly 1,805 CNY, and the team plan at 999 dollars is about 7,243 CNY. These prices are quite high for our budget.

That said, I agree with you that focusing on creating a "completely open-sourced, fully-fledged docs-template based on shadcn" is a great motivation. I understand how mentioning the cost might come across as aggressive, so I’ll suggest to Tony that he refines his wording to better convey our intent.

Thank you for your support and encouragement. We’ll keep pushing forward with this project!

Best regards,  
Asyncfox
