### ISSUE TITLE
Syntax highlighting not working for languages other than JavaScript and TypeScript

### ISSUE THREAD

**Issue by deepakgohil9** [ZTL-UwU/shadcn-docs-nuxt#12]
## Title: Syntax highlighting not working for languages other than JavaScript and TypeScript

**Description:**

I'm experiencing an issue with syntax highlighting. When I use code blocks with the following formatting:

>\```ts
>... (TypeScript code here) ...
>\```

or

>\```js
>... (JavaScript code here) ...
>\```

the syntax highlighting works perfectly. However, when I try to use code blocks for other languages, such as C++, the syntax highlighting is not applied.

**Expected behavior:**

Syntax highlighting should be applied for all supported languages within code blocks, regardless of the specific language used. This includes proper formatting for keywords, functions, variables, and other code elements.

**Actual behavior:**

Syntax highlighting only works for JavaScript and TypeScript code blocks. Code blocks for other languages, such as C++, appear as plain text without any highlighting.

**Screenshot:**
![image](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/93052295/0311375e-6495-46d5-98e4-2653ad3079f7)

**Request:**

Please investigate this issue and fix the syntax highlighting for languages other than JavaScript and TypeScript.

**Comment by ZTL-UwU** [comment]
You need to add the languages you want to highlight in your `nuxt.config.ts`.

```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  extends: ['shadcn-docs-nuxt'],
  compatibilityDate: '2024-07-06',
  content: {
    highlight: {
      langs: ['c', 'cpp'],
    },
  },
});
```

See https://content.nuxt.com/get-started/configuration#highlight.

**Comment by ZTL-UwU** [comment]
If you're still having issues with it, feel free to reopen the issue.
