### ISSUE TITLE
Allow customizing the title of breadcrumb

### ISSUE THREAD

**Issue by HADB** [ZTL-UwU/shadcn-docs-nuxt#14]
Hi, thanks for this great project! 

I have an issue about customizing the title of breadcrumbs.

I found that the title of breadcrumb is generated from path:

https://github.com/ZTL-UwU/shadcn-docs-nuxt/blob/03cf31e81c27d2d08c621eb175bb2248da099902/components/layout/Breadcrumb.vue#L28-L40

Is it better to use the titles in markdown files and `_dir.yml` files?

**Comment by ZTL-UwU** [comment]
Yes indeed, thanks for the idea!
