### ISSUE TITLE
How to use in existing project

### ISSUE THREAD

**Issue by peoray** [ZTL-UwU/shadcn-docs-nuxt#15]
Thanks for this template ;)

The guide does not show how to use it in an existing project. Is it possible to do so?

**Comment by ZTL-UwU** [comment]
Technically it is possible. You can:
1. Install `shadcn-docs-nuxt`
2. Add `extends: ['shadcn-docs-nuxt']` in your `nuxt.config`
3. Copy [`assets/`](https://github.com/ZTL-UwU/shadcn-docs-nuxt-starter/tree/main/assets/), [`app.config.ts`](https://github.com/ZTL-UwU/shadcn-docs-nuxt-starter/blob/main/app.config.ts), and [`tailwind.config.ts`](https://github.com/ZTL-UwU/shadcn-docs-nuxt-starter/blob/main/tailwind.config.ts) from the starter template into your project root directory.

However, `shadcn-docs-nuxt` contains `index.vue` and `[...slug].vue` in `pages/` as a nuxt layer, so I'm not sure if it works in existing projects.

**Comment by ZTL-UwU** [comment]
Closing this as using shadcn-docs-nuxt with existing project is not the recommended use case.
