### ISSUE TITLE
useConfig is not defined

### ISSUE THREAD

**Issue by sajadhzj** [ZTL-UwU/shadcn-docs-nuxt#16]
i Installation step by step but when run app say useConfig is not defined , how fix this

`
Nuxt project info:                                                                                                              10:36:35 AM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.20.2
- Nuxt Version:     3.11.1
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  npm@10.5.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------
`

**Comment by ZTL-UwU** [comment]
Did you installed using the starter template?
