### ISSUE TITLE
Allow to hide "footnotes" in the toc

### ISSUE THREAD

**Issue by xarthurx** [ZTL-UwU/shadcn-docs-nuxt#20]
## Problem
The `toc` now adds an additional `Footnotes` section if there're footnotes on inside the markdown file.

However, due to the fact that there's usually little space between the footnotes section and the previous section (pic below):
![image](https://github.com/user-attachments/assets/9f64205e-4798-4450-9917-250036feee14)

A common practice is to **add an additional section title** (footnote, reference, etc.) in the `.md` file:
```
## Demo File
<-!-- text of the this section -->

## Footnotes
<!-- nuxt will render the footnotes here. -->
```
which will result the rendering as:
![image](https://github.com/user-attachments/assets/782385da-47fe-4228-869e-bbfeadb834fd)

But this will render additional section in the `toc`:
![image](https://github.com/user-attachments/assets/f924ba4d-053e-40ae-bd8a-6a9a155033d6)

## Proposed solution:
add a boolean option `hide_footnote` to the `toc` in `app.config.ts`.

**Comment by ZTL-UwU** [comment]
You can set the **Footnots** title `id` to `hide-toc` to hide it from the toc.

```md
:h2[Footnotes]{id="hide-toc"}
```

**Comment by xarthurx** [comment]
> Update to `0.4.7` and you can set the **Footnots** title `id` to `hide-toc` to hide it from the toc.
> 
> ```
> :h2[Footnotes]{id="hide-toc"}
> ```
> 
> https://shadcn-docs.nuxt.dev/getting-started/writing/markdown#hide-title-from-toc

Where do you put the above line? in the `app.config.ts`?
The default `Footnotes` are generated automatically.

**Comment by ZTL-UwU** [comment]
> Or do you mean I should hide my own one and use the default on in the toc? (This will prevent the user from changing the title...)

Yes, I meant that you should hide your own header. That is to replace `## Footnotes` with `:h2[Footnotes]{id="hide-toc"}`.

Unfortunatlly the toc is generated by nuxt content so I can not make it hide anything.
