### ISSUE TITLE
enhancement: customize footer

### ISSUE THREAD

**Issue by xarthurx** [ZTL-UwU/shadcn-docs-nuxt#25]
The current footer is a bit limited for displaying rich info.
For instance:
![image](https://github.com/user-attachments/assets/1c11c322-445d-4826-a177-f571226731db)

Using custom icons is not allowed.

## Proposal
1. Enhance the API for richer options: customize icons, imgs, etc.
2. It would be even better to have some documentation on using user-written "vue-component" to replace the `header.vue` and `footer.vue`, as these are often needed for various reasons.

**Comment by ZTL-UwU** [comment]
Thanks for the proposals!

> 1. Enhance the API for richer options: customize icons, imgs, etc.

We will track this in #26 

> 2. It would be even better to have some documentation on using user-written "vue-component" to replace the header.vue and footer.vue, as these are often needed for various reasons.

You can already do that by adding `/components/layout/Footer.vue` in your project. It will replace the footer component from shadcn-docs. In fact, any component in shadcn-docs is replacable with this method thanks to nuxt layers.

I think i'll add a section in the docs to explain this later on.

**Comment by ZTL-UwU** [comment]
https://shadcn-docs.nuxt.dev/api/advanced/override
