### ISSUE TITLE
Static build doesn't work

### ISSUE THREAD

**Issue by bgervan** [ZTL-UwU/shadcn-docs-nuxt#27]
With `nuxt generate` and `nuxt preview` it doesn't show the website just the file list. 

Any clue why? Is it due to some misconfiguration or the project is not suitable for ssg for some reason?

<img width="655" alt="image" src="https://github.com/user-attachments/assets/20ba57b8-d667-4189-a0ff-cd28bb9e60c6">

**Comment by ZTL-UwU** [comment]
shadcn-docs uses the [document driven mode](https://content.nuxt.com/document-driven/introduction) from nuxt content, so it is not possible to use prerender pages. The work around is to use `nuxt build` instead, and you can set all the routes to `prerender: true`. 

```ts
routeRules:{
  '/**': { prerender: true }
}
```
