### ISSUE TITLE
[request]: new props for Alert

### ISSUE THREAD

**Issue by ijkml** [ZTL-UwU/shadcn-docs-nuxt#28]
Hi, can I send a PR to make `Alert` and `Callout` auto-detect internal links and/or accept an "external" prop?

**Comment by ZTL-UwU** [comment]
I don't quite understand what you mean. Can you explain further what you want the feature to be like?

**Comment by ijkml** [comment]
Here
https://github.com/ZTL-UwU/shadcn-docs-nuxt/blob/main/components%2Fcontent%2FAlert.vue#L50

Every alert link forces a full page load whether or not it's an internal link because of `external`.

With an "external" option, you can set it to false and use Nuxt routing. IMO, I think false should be default. Also, you could detect "http" in the link and set external to true.

**Comment by ZTL-UwU** [comment]
Fixed in 7af13b229a98340472a38e2abac3cfc5ed8db24b. It will now auto detect external links and there is an `external` prop just in case.

**Comment by ijkml** [comment]
Nice, 🚀 thanks!
