### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by guifeliper** [ZTL-UwU/shadcn-docs-nuxt#31]
I am new to Nuxt and Vue, but why can I not access the files on app whenever I start a template? How can I edit them if I don't have access to it? 

Actual result: 
<img width="391" alt="image" src="https://github.com/user-attachments/assets/5e605bd6-8007-4ce7-bf8a-db040af3aaf4">

Expected result: 
<img width="255" alt="image" src="https://github.com/user-attachments/assets/bbd8ad69-9dd3-41d8-ae13-a17c5dca673e">

**Comment by ZTL-UwU** [comment]
shadcn-docs-nuxt is a [Nuxt Layer](https://nuxt.com/docs/getting-started/layers). The starter template extends the `shadcn-docs-nuxt` package (which contains the files in the second screenshot).

To override you can create a custom vue component in your project with the same path as the original component. See https://shadcn-docs.nuxt.dev/api/advanced/override.
