### ISSUE TITLE
Vue warn: Extraneous non-props attributes

### ISSUE THREAD

**Issue by ManUtopiK** [ZTL-UwU/shadcn-docs-nuxt#34]
Hi!
I've got a lot of vue warn like this one :

![image](https://github.com/user-attachments/assets/dae3f2b7-4815-402d-b044-36563d4801a8)

I investigate a little bit but can't find the cause of this issue.

**Comment by ZTL-UwU** [comment]
https://github.com/nuxt/devtools/issues/722

**Comment by ZTL-UwU** [comment]
Update `@nuxt/devtools` to `1.5.2` should make the warnings disappear.

**Comment by jonasfroeller** [comment]
```
WARN  [Vue warn]: Extraneous non-props attributes (data-v-14ce88ff) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
```

![image](https://github.com/user-attachments/assets/09919767-ecbd-4228-86cc-c5cfeefec960)
