### ISSUE TITLE
How to customize URL

### ISSUE THREAD

**Issue by peoray** [ZTL-UwU/shadcn-docs-nuxt#37]
@ZTL-UwU how can I customize the URL as well

The path is always top level section and then the children like getting-started/introduction 

Can I have like a docs/introduction, docs/components/bento-grid

This is so that the breadcrumb I'll customize will tally with the URL as well

**Comment by ZTL-UwU** [comment]
You can just create a folder called `docs` in the content folder.

```
content/
  index.md
  docs/
    introduction.md
    components/
      bento-grid.md
```

**Comment by peoray** [comment]
I'd still like it to have the top level heading though.

so:

**Getting Started**
- introduction 
- installation 

**Components** 
- bento-grid

etc.

**Comment by ZTL-UwU** [comment]
Hmm, I don't think this level of customization of the URL is possible through nuxt content's file based routing.

However, what you can do perhaps is to override the sidebar and maintain the links manually.

https://github.com/unovue/shadcn-vue/blob/ff6d9d0da657a41582beec2b63d6b7e5683ddc8f/apps/www/.vitepress/theme/layout/DocsLayout.vue

https://github.com/unovue/shadcn-vue/blob/ff6d9d0da657a41582beec2b63d6b7e5683ddc8f/apps/www/.vitepress/theme/config/docs.ts

**Comment by peoray** [comment]
![Screenshot 2024-10-09 at 6 06 17 PM](https://github.com/user-attachments/assets/d4bf7789-1b6f-4488-b211-9785853d3bef)

This is not the behaviour I want. Is it possible to have this without having docs as a top-level heading?
