### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#40]
Could just work like:

```mdx
:button{title="button" leftIcon="lucide:globe" to="/" <any other link atttributes>}
:button{title="button2" rightIcon="lucide:link" variant="outline" to="/"}
```

`leftIcon` & `rightIcon` are optional.

**Comment by ZTL-UwU** [comment]
Added in `0.6.5`. [Usage Guide](https://shadcn-docs-nuxt.vercel.app/getting-started/writing/components#button-link)
