### ISSUE TITLE
No mobile TOC

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#43]
On mobile there is no page table of contents (only list of pages and the nav). Not sure if this is a stylistic choice or if somebody forgot something.

**Comment by ZTL-UwU** [comment]
There is mobile TOC. You have to implicitly turn it on with `enableInMobile: true` in the config. See https://shadcn-docs-nuxt.vercel.app/api/configuration/shadcn-docs#toc.

This is a stylistic choice as the original shadcn/ui documentation does this.
