### ISSUE TITLE
feat: extend tabs with selectable list of tabs

### ISSUE THREAD

**Issue by nikeshparajuli** [ZTL-UwU/shadcn-docs-nuxt#46]
### Describe the feature

It would be nice to have a selectable list of tabs from a dropdown menu. All other functionality would remain the same as the current Tab variants.

Bonus points for the search functionality. Like in the current tabs implementation, the first tab in the list would be selected by default.

![CleanShot 2024-10-27 at 21 51 30@2x](https://github.com/user-attachments/assets/0e7c8d6b-0c46-4748-8db4-0da13904d717)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Usage: https://shadcn-docs-nuxt.vercel.app/components/docs/tabs#combobox-style.

Will be release soon in `v0.7.5`.

**Comment by nikeshparajuli** [comment]
@ZTL-UwU This looks awesome! A slight improvement request if possible:
* Be able to override the search label placeholder instead of generic 'Search Tabs...' to make it easier for readers what those options are.. plus adds/extends context of the docs too

**Comment by ZTL-UwU** [comment]
> @ZTL-UwU This looks awesome! A slight improvement request if possible:
> 
> * Be able to override the search label placeholder instead of generic 'Search Tabs...' to make it easier for readers to understand what those options are.. plus adds/extends context of the docs too

Added in [`e0008b3`](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/e0008b305d1296cacd36da0671cfbd17a3335f87).
