### ISSUE TITLE
bug: `alert` without `type` default to the info style

### ISSUE THREAD

**Issue by xarthurx** [ZTL-UwU/shadcn-docs-nuxt#47]
### Environment

  System:
    OS: Linux 5.15 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (24) x64 Intel(R) Core(TM) i9-9920X CPU @ 3.50GHz
    Memory: 28.41 GB / 31.20 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.7.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.33 - ~/.bun/bin/bun
  npmPackages:
    nuxt: ^3.13.2 => 3.13.2

### Describe the bug

https://shadcn-docs-nuxt.vercel.app/components/docs/alert

Using the alert, when just use:
```
::alert
blabla
::
```

OR
```
::alert{}
blabla
::
```

The default style is not black (as shown in the doc), but the `info` style (blue)

**Comment by ZTL-UwU** [comment]
What is your `vue` version?

**Comment by xarthurx** [comment]
> What is your `vue` version?

`vue3` but not sure about the small version, as I use `nuxt` directly.

**Comment by ZTL-UwU** [comment]
Please install vue explicitly. shadcn-docs-nuxt requires `vue >= 3.5` to work.
