### ISSUE TITLE
feat: `edit this page` link in toc & navigation section

### ISSUE THREAD

**Issue by ZTL-UwU** [ZTL-UwU/shadcn-docs-nuxt#49]
Allow users to add **edit this page** links to both the toc section and the previous/next page section.

- [x] Link at the end of each page [`ded42e7`](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/ded42e797da834f7c7cf07c9ebd9638c02e9e806)
- [x] Control on/off via front-matter [`52d53c1`](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/52d53c169e62f1df0e855eef70966764d187cf7e)
- [x] Link in TOC [`ca60053`](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/ca6005314170b2ab8cdf7ecbe4d4be7916af2255) #48

**Comment by ZTL-UwU** [comment]
Usage guide: https://shadcn-docs-nuxt.vercel.app/api/configuration/edit-link.

**Comment by mdobydullah** [comment]
Thank you @ZTL-UwU. Really appreciated. 👍
