### ISSUE TITLE
feat: Add code lines

### ISSUE THREAD

**Issue by FrankOldmoon** [ZTL-UwU/shadcn-docs-nuxt#55]
### Describe the feature

Can you add the feature for displaying code lines, tks~
<img width="819" alt="image" src="https://github.com/user-attachments/assets/09be7981-1fed-4e73-9e82-b1e91644b32c">

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in 404e5a465da057f4282be06fb3d0e8bd23384c16, published in `v0.7.8`.
Usage guide: https://shadcn-docs-nuxt.vercel.app/components/prose#code-block

**Comment by FrankOldmoon** [comment]
Thanks a lot~

**Comment by FrankOldmoon** [comment]
天呐，你居然是深中的，现在还在读的高中生？我是深中光明的信息老师，能不能留个邮箱，想联系一下你，你的shadcn-docs给我帮助很大~这是我的邮箱：oldmoon1024@foxmail.com
