### ISSUE TITLE
feat: heroImage option for heroAlt

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#59]
### Describe the feature

What the title says. Add an option for a hero image/video to the right of the hero.

Image can be placed above the hero on mobile.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in `v0.8.1`.

Usage guide: https://shadcn-docs-nuxt.vercel.app/components/page/hero-alt
