### ISSUE TITLE
feat: Image option for cards

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#60]
### Describe the feature

Add an image option for cards like what [Mintlify has](https://mintlify.com/docs/content/components/cards#props), where the card content is a bar under of the image:

![image](https://github.com/user-attachments/assets/ce9e1119-f76e-4a35-a872-242318c0411a)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in `v0.8.1`.

Usage guide: https://shadcn-docs-nuxt.vercel.app/components/docs/card
