### ISSUE TITLE
How do we resize the sidebar so that long texts don't appear as three dots?

### ISSUE THREAD

**Issue by YasinSpace** [ZTL-UwU/shadcn-docs-nuxt#61]
### Describe the feature

In this project, what file or files should I put in order to change the size of the sidebar where the articles and categories are grouped, such as so that the titles do not appear as three dots for texts with long titles?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in `v0.8.1`.

Usage:
```yml
---
navTruncate: false
title: very very very long title
---

// ...
```

**Comment by YasinSpace** [comment]
another idea, can we have an option to make the title text in center? not text from left to right?
