### ISSUE TITLE
feat: Banner option in app.config.ts

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#62]
### Describe the feature

Possibility of having a banner at the top of the page on all pages (similar to Material for MkDocs or Fumadocs) with different styles, an icon prop, and an option for if it can be closed.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Ast3risk-ops** [comment]
Noticed this was added, closing.

**Comment by ZTL-UwU** [comment]
For the record, added in dfbc2433baae887cd7deeb7517e0a9f62450d081, released in `v0.8.3`
Usage guide: https://shadcn-docs-nuxt.vercel.app/api/configuration/banner
