### ISSUE TITLE
bug: Banner hides Nuxt loading indicator

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#69]
### Environment

```sh
  System:
    OS: Linux 6.12 EndeavourOS
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 20.68 GB / 31.21 GB
    Container: Yes # Not sure what this means but I'm not using a docker container
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 23.3.0 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.9.2 - /usr/bin/npm
    pnpm: 9.14.4 - /usr/bin/pnpm
    bun: 1.1.38 - ~/.bun/bin/bun
```

### Describe the bug

The Nuxt loading indicator disappears if the banner is enabled.

### Reproduction

https://github.com/ast3risk-ops/archiver/tree/main/www

https://github.com/user-attachments/assets/164e307d-ae4d-4eab-a013-a173e3de9121

### Additional context

I have both enabled.

### Logs

```shell-script
There are no errors.
```

**Comment by ZTL-UwU** [comment]
Hi, I've checked your site and the loading indicator is visible. It is not seen in the video because the loading time is too short and the loading indicator is not triggered.
