### ISSUE TITLE
feat: disable link icon on cards

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#70]
### Describe the feature

Option to disable the upper-right arrow icon on a card with a link property.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in [92a8940](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/92a89404a4beeb0154f301106bb22628fa75e9a3)
