### ISSUE TITLE
feat: horizontal cards

### ISSUE THREAD

**Issue by Ast3risk-ops** [ZTL-UwU/shadcn-docs-nuxt#71]
### Describe the feature

Option to make smaller horizontal cards for use in pages similar to what Mintlify has:

![image](https://github.com/user-attachments/assets/f446dfd6-7f94-4c92-ac10-1be482e5a6ed)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
Added in [6277011](https://github.com/ZTL-UwU/shadcn-docs-nuxt/commit/62770113481ff5a372b668e5739ae2e715bad4d3)
