### ISSUE TITLE
feat: unwrapped aside links? 

### ISSUE THREAD

**Issue by nikeshparajuli** [ZTL-UwU/shadcn-docs-nuxt#80]
### Describe the feature

Hi, is there an option to unwrap aside links already? If not, would you mind making this customizable? It helps to find links with longer titles easily.

Current:
![CleanShot 2024-12-30 at 15 25 54](https://github.com/user-attachments/assets/be822696-76f0-4864-8f02-dc51e1e01ce7)

Expected:
![CleanShot 2024-12-30 at 15 26 10](https://github.com/user-attachments/assets/d8ce39dc-b185-4619-9088-b41af20ca1c4)

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by ZTL-UwU** [comment]
```md
---
navTruncate: false
title: very very very long title
---

// ...
```

**Comment by nikeshparajuli** [comment]
Thank you, @ZTL-UwU! Hadn't upgraded the package for over a month or so otherwise I'd have found out sooner. However, upon upgrading, I cannot toggle collapse/expand folders on the aside, or switch to dark/light mode. Is there something I'm missing?

**Comment by ZTL-UwU** [comment]
Hi, @nikeshparajuli, I've encountered this as well, and I solved it by completely reinstalled the dependencies (removing the `node_modules` and the lock file).

**Comment by nikeshparajuli** [comment]
Thank you, that worked!
