### ISSUE TITLE
Failed to fetch dynamically imported module: http://localhost:3000/_nuxt/node_modules/shadcn-docs-nuxt/pages/index.vue

### ISSUE THREAD

**Issue by CodyBontecou** [ZTL-UwU/shadcn-docs-nuxt#9]
Fresh install using the command `npx nuxi@latest init nuxtfast -t github:ZTL-UwU/shadcn-docs-nuxt-starter` and then running `npm run dev` errors. The page loads for a split second, then errors with `Failed to fetch dynamically imported module: http://localhost:3000/_nuxt/node_modules/shadcn-docs-nuxt/pages/index.vue`

![CleanShot 2024-06-25 at 09 06 01](https://github.com/ZTL-UwU/shadcn-docs-nuxt/assets/20440899/86772023-be16-425d-9c16-fea5c9f297d4)

**Comment by CodyBontecou** [comment]
Hmm, nevermind. Just re-installed it and it's working now.

**Comment by rmakara** [comment]
It's still happening to me. :(

**Comment by CodyBontecou** [comment]
Hey @rmakara, have you ran the command `npx nuxi@latest init -t github:ZTL-UwU/shadcn-docs-nuxt-starter`? 

I think my issue is I ran the init command with an output directory. Deleting the directory and re-running the command provided fixed it for me.
